version: "3"
services:
  nginx:
    container_name: nginx
    build: ./docker/local/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage/logs/nginx:/var/log/nginx

  app:
    container_name: app
    build: ./docker/local/php
    volumes:
      - ./docker/local/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www
  node:
    container_name: node
    build: ./docker/local/node
    volumes:
      - ./src:/var/www
    ports:
      - "3000:3000"
    tty: true

  db:
    container_name: db
    build: ./docker/local/mysql
    ports:
      - "3309:3306"
    volumes:
      - ./docker/local/mysql/my.cnf:/etc/mysql/my.cnf
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db-volume: